### PR TITLE
Addinga a stresser script to test wallet functions

### PR DESCRIPTION
**Pull request by chasingkirkjufell**
The script is written in bash version 5.0.3. OSX users may need to install gshuf and substitude all shuf with gshuf. The users will need to specify the navpath and then configure the tests as needed in the script.

### CODE REVIEW

**Comment by aguycalled** [comment]
<s>Mac users also need to subsitute line 445 with

```bash
	echo ${local_array_best_hash[@]} $(printf "%s\n" "${local_array_best_hash[@]}" | LC_CTYPE=C sort -z -u | uniq | grep -n -c .)
```</s>

**Comment by chasingkirkjufell** [comment]
> Mac users also need to subsitute line 445 with
> 
> ```shell
> 	echo ${local_array_best_hash[@]} $(printf "%s\n" "${local_array_best_hash[@]}" | LC_CTYPE=C sort -z -u | uniq | grep -n -c .)
> ```

do you mean substitute line 474
`if [ $(printf "%s\000" "${local_array_best_hash[@]}" | LC_CTYPE=C sort -z -u | uniq | grep -n -c .) -gt 1 ];`
with 
`if [ $(printf "%s\n" "${local_array_best_hash[@]}" | LC_CTYPE=C sort -z -u | uniq | grep -n -c .) -gt 1 ];`
?

And I think maybe the same for line 499 when checking state hash? did you also change line 499?
`if [ $(printf "%s\000" "${local_array_statehash[@]}" | LC_CTYPE=C sort -z -u | uniq | grep -n -c .) -gt 1  ];`

**Comment by aguycalled** [comment]
yes, sorry i confused it with a debug line from my script. the lines from your script which should be substituted are 478 and 503

**Comment by chasingkirkjufell** [comment]
Yes, well i referenced the wrong lines as well. :P I would like to change the file name of stresser. I guess the only way is to create a different PR and close this one?

**Comment by aguycalled** [comment]
if you mean the name of the script file, you can make a new commit with the new name (removing the old file and adding the new one)

**Pull request merged**
